"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { doc, getDoc, writeBatch } from "firebase/firestore";
import { Camera, ChevronLeft, KeyRound, LockKeyhole, MapPin, ShieldCheck, UnlockKeyhole } from "lucide-react";
import AppHeader from "@/components/AppHeader";
import Footer from "@/components/Footer";
import { useAuth } from "@/components/AuthProvider";
import { db } from "@/lib/firebase";
import type { Booking, Vehicle } from "@/lib/types";
import { bookingStatusClass, bookingStatusLabel, dateTime, money, reservationWindow } from "@/lib/utils";

export default function BookingDetailPage() {
  const params = useParams<{ id: string }>(); const router = useRouter(); const { user, profile, loading: authLoading } = useAuth();
  const [booking, setBooking] = useState<Booking | null>(null); const [vehicle, setVehicle] = useState<Vehicle | null>(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => { try { const snap = await getDoc(doc(db, "bookings", params.id)); if (!snap.exists()) return; const data = { id: snap.id, ...(snap.data() as Omit<Booking, "id">) }; setBooking(data); const vs = await getDoc(doc(db, "vehicles", data.vehicleId)); if (vs.exists()) setVehicle({ id: vs.id, ...(vs.data() as Omit<Vehicle, "id">) }); } catch (e) { console.error(e); } finally { setLoading(false); } };
  useEffect(() => { if (authLoading) return; if (!user) { router.replace(`/login?next=${encodeURIComponent(`/reserva/${params.id}`)}`); return; } load(); }, [user, authLoading, params.id, router]);
  const windowState = useMemo(() => booking ? reservationWindow(booking.startAt, booking.endAt) : null, [booking]); const isOwner = !!booking && !!user && booking.userId === user.uid; const isAdmin = profile?.role === "admin"; const canInspectInitial = !!booking && ["pendiente", "confirmada"].includes(booking.status) && !booking.inspectionInitialComplete; const canInspectFinal = !!booking && ["activa", "confirmada"].includes(booking.status) && !!booking.inspectionInitialComplete && !booking.inspectionFinalComplete; const canOpen = !!booking && booking.status === "confirmada" && booking.paymentStatus === "pagado" && !!booking.inspectionInitialComplete && !!windowState?.active;
  const cancel = async () => { if (!booking || !confirm("¿Quieres cancelar esta reserva?")) return; setBusy(true); try { const now = new Date().toISOString(); const batch = writeBatch(db); batch.update(doc(db, "bookings", booking.id), { status: "cancelada", updatedAt: now }); batch.update(doc(db, "availability", booking.id), { status: "cancelada", updatedAt: now }); await batch.commit(); await load(); } catch (e) { console.error(e); setMessage("No se ha podido cancelar la reserva."); } finally { setBusy(false); } };
  const telematics = (command: "open" | "close") => { if (!canOpen && command === "open") return setMessage("Todavía no se cumplen todas las condiciones para abrir el vehículo."); setMessage(vehicle?.telematicsEnabled ? "El vehículo está preparado para telemática, pero el servidor todavía no está conectado." : `${command === "open" ? "Apertura" : "Cierre"} remota todavía no configurada.`); };
  if (authLoading || loading) return <><AppHeader /><div className="loading-screen"><div className="loader" /></div></>; if (!booking || (!isOwner && !isAdmin)) return <><AppHeader /><main className="page-main"><div className="container"><div className="client-empty"><strong>Reserva no disponible</strong><p>No existe o no tienes permiso para verla.</p></div></div></main></>;
  const action = canInspectInitial ? { label: "Hacer inspección", href: `/reserva/${booking.id}/inspeccion?tipo=inicial`, icon: Camera } : canOpen ? { label: "ABRIR VEHÍCULO", icon: UnlockKeyhole } : canInspectFinal ? { label: "Finalizar alquiler", href: `/reserva/${booking.id}/inspeccion?tipo=final`, icon: Camera } : { label: "Cerrar vehículo", icon: LockKeyhole };
  return <div className="page"><AppHeader /><main className="client-app-main"><div className="container active-booking-container"><Link href="/mis-reservas" className="back-link"><ChevronLeft /> Mis reservas</Link><section className="active-booking-hero"><div className="active-booking-image">{booking.vehicleImageUrl ? <img src={booking.vehicleImageUrl} alt={booking.vehicleName} /> : <div className="booking-image-placeholder"><span>CALENDA</span><strong>{booking.vehicleName}</strong></div>}</div><div className="active-booking-copy"><span className={bookingStatusClass(booking.status)}>{bookingStatusLabel(booking.status)}</span><h1>{booking.vehicleName}</h1><p className="booking-plate">Matrícula · {booking.vehiclePlate}</p><div className="active-booking-info"><div><span>Recogida</span><strong>{dateTime(booking.startAt)}</strong></div><div><span>Devolución</span><strong>{dateTime(booking.endAt)}</strong></div><div><span>Ubicación</span><strong><MapPin /> {booking.pickupCity}</strong></div></div>{message && <div className="notice notice-info">{message}</div>}{action.href ? <Link href={action.href} className="active-primary-action"><action.icon /> {action.label}</Link> : <button className="active-primary-action" onClick={() => telematics(canOpen ? "open" : "close")} disabled={!canOpen && action.label === "ABRIR VEHÍCULO"}><action.icon /> {action.label}</button>}<div className="active-secondary-actions">{booking.inspectionInitialComplete && <Link href={`/reserva/${booking.id}/inspeccion?tipo=inicial`}><Camera /> Ver inspección inicial</Link>}{booking.inspectionFinalComplete && <Link href={`/reserva/${booking.id}/inspeccion?tipo=final`}><Camera /> Ver inspección final</Link>}{["pendiente", "confirmada"].includes(booking.status) && <button onClick={cancel} disabled={busy}>Cancelar reserva</button>}</div></div></section><section className="active-booking-summary"><div><span>Importe</span><strong>{money(booking.amount)}</strong></div><div><span>Fianza</span><strong>{money(booking.deposit)}</strong></div><div><span>Pago</span><strong>{booking.paymentStatus === "pagado" ? "Completado" : "Pendiente"}</strong></div></section><div className="notice notice-warning active-note"><KeyRound /> El acceso remoto se mantiene sujeto a las condiciones actuales de la reserva y a la integración telemática del vehículo.</div></div></main><Footer /></div>;
}
