"use client";

import Link from "next/link";
import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { doc, getDoc, updateDoc } from "firebase/firestore";
import { getDownloadURL, ref, uploadBytes } from "firebase/storage";
import { Camera, Check, ChevronLeft, Image as ImageIcon } from "lucide-react";
import AppHeader from "@/components/AppHeader";
import { useAuth } from "@/components/AuthProvider";
import { db, storage } from "@/lib/firebase";
import type { Booking, InspectionPhoto } from "@/lib/types";
const SLOTS = [["frontal", "Frontal"], ["trasera", "Trasera"], ["lateral-izquierdo", "Lateral izquierdo"], ["lateral-derecho", "Lateral derecho"], ["esquina-delantera", "Esquina delantera"], ["esquina-trasera", "Esquina trasera"], ["interior", "Interior"], ["cuadro", "Cuadro / combustible / km"]] as const;
export default function InspectionPage() { const params = useParams<{ id: string }>(); const router = useRouter(); const searchParams = useSearchParams(); const type = searchParams.get("tipo") === "final" ? "final" : "inicial"; const { user, loading: authLoading } = useAuth(); const [booking, setBooking] = useState<Booking | null>(null); const [photos, setPhotos] = useState<InspectionPhoto[]>([]); const [uploading, setUploading] = useState<string | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
 useEffect(() => { if (authLoading) return; if (!user) { router.replace(`/login?next=${encodeURIComponent(`/reserva/${params.id}/inspeccion?tipo=${type}`)}`); return; } (async () => { try { const snap = await getDoc(doc(db, "bookings", params.id)); if (!snap.exists()) return; const data = { id: snap.id, ...(snap.data() as Omit<Booking, "id">) }; if (data.userId !== user.uid) return; setBooking(data); setPhotos(type === "inicial" ? data.initialPhotos || [] : data.finalPhotos || []); } catch (e) { console.error(e); } finally { setLoading(false); } })(); }, [user, authLoading, params.id, router, type]);
 const complete = useMemo(() => SLOTS.every(([slot]) => photos.some((p) => p.slot === slot)), [photos]); const upload = async (slot: string, event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || !booking || !user) return; if (!file.type.startsWith("image/")) return setError("Solo se admiten imágenes."); if (file.size > 12 * 1024 * 1024) return setError("La fotografía no puede superar 12 MB."); setError(""); setUploading(slot); try { const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, "_"); const path = `booking-inspections/${user.uid}/${booking.id}/${type}/${slot}-${Date.now()}-${safeName}`; const storageRef = ref(storage, path); await uploadBytes(storageRef, file, { contentType: file.type }); const url = await getDownloadURL(storageRef); const nextPhoto: InspectionPhoto = { slot, name: safeName, url, path, uploadedAt: new Date().toISOString() }; const next = [...photos.filter((p) => p.slot !== slot), nextPhoto]; setPhotos(next); await updateDoc(doc(db, "bookings", booking.id), { [type === "inicial" ? "initialPhotos" : "finalPhotos"]: next, updatedAt: new Date().toISOString() }); } catch (e) { console.error(e); setError("No se ha podido subir la fotografía."); } finally { setUploading(null); } }; const finish = async () => { if (!booking || !complete) return; try { await updateDoc(doc(db, "bookings", booking.id), { [type === "inicial" ? "inspectionInitialComplete" : "inspectionFinalComplete"]: true, updatedAt: new Date().toISOString() }); router.push(`/reserva/${booking.id}`); } catch (e) { console.error(e); setError("No se ha podido completar la inspección."); } };
 if (authLoading || loading) return <><AppHeader /><div className="loading-screen"><div className="loader" /></div></>; if (!booking) return <><AppHeader /><main className="client-app-main"><div className="container"><div className="client-empty"><strong>Inspección no disponible</strong></div></div></main></>;
 return <div className="page"><AppHeader /><main className="client-app-main inspection-main"><div className="container inspection-container"><Link href={`/reserva/${booking.id}`} className="back-link"><ChevronLeft /> Volver a la reserva</Link><div className="inspection-heading"><div><p className="eyebrow">{type === "inicial" ? "Antes de conducir" : "Antes de devolver"}</p><h1>Revisa el vehículo</h1><p>Haz estas fotografías antes de comenzar.</p></div><strong className="inspection-progress">{photos.length} / {SLOTS.length}</strong></div>{error && <div className="form-error">{error}</div>}<div className="inspection-progress-line"><span style={{ width: `${Math.min(100, photos.length / SLOTS.length * 100)}%` }} /></div><div className="inspection-grid">{SLOTS.map(([slot, label]) => { const photo = photos.find((p) => p.slot === slot); return <article className={`inspection-slot ${photo ? "is-complete" : ""}`} key={slot}><div className="inspection-photo">{photo ? <img src={photo.url} alt={label} /> : <ImageIcon />}</div><div className="inspection-slot-copy"><strong>{photo && <Check />} {label}</strong><label className="inspection-camera-button"><Camera /> {photo ? "Repetir foto" : "Hacer foto"}<input type="file" accept="image/*" capture="environment" disabled={uploading !== null} onChange={(e) => upload(slot, e)} /></label>{uploading === slot && <small>Subiendo fotografía...</small>}</div></article>; })}</div><button className="active-primary-action inspection-finish" disabled={!complete || uploading !== null} onClick={finish}>{type === "inicial" ? "Continuar con el alquiler" : "Completar devolución"}</button></div></main></div>; }
